Updates and fixes. License added

diff --git a/oc-login b/oc-login
--- a/oc-login
+++ b/oc-login
@@ -11,6 +11,7 @@ set -o pipefail
 DOC="https://github.com/openshift-evangelists/oc-login/blob/master/README.adoc"
 SCRIPT_NAME=$(basename "$0")
 OC_BINARY=${OC_BINARY:-"oc"}
+TIMEOUT=${OC_LOGIN_TIMEOUT:-"1s"}
 
 ################## AUXILIARY FUNCTIONS
 #
@@ -71,21 +72,35 @@ function list.help {
 
 function login {
   local _arg1=${1:-}
+  local _retCode
 
-  set -x
   [ "$_arg1" == "-h" ] || [ "$_arg1" == "--help" ] && ${FUNCNAME[0]}.help && return 0
   
-  ${OC_BINARY} whoami > /dev/null 2>&1
-  local _retCode=$?
+  ${OC_BINARY} whoami --request-timeout=$TIMEOUT > /dev/null 2>&1
+  _retCode=$?
   if [ $_retCode -ne 0 ]; then
-    local _ctx=$(${OC_BINARY} whoami -c)
-    local _cluster=$(${OC_BINARY} whoami --show-server)
-    local _user=$(${OC_BINARY} config view -o jsonpath='{.contexts[?(@.name == "'${_ctx}'")].context.user}' | cut -f 1 -d '/')
-    echo "oc login ${_cluster} -u ${_user}"
-    ${OC_BINARY} login ${_cluster} -u ${_user}
-    ${OC_BINARY} config delete-context ${_ctx} > /dev/null 2>&1
-    ${OC_BINARY} config rename-context $(${OC_BINARY} whoami -c) ${_ctx} > /dev/null 2>&1
-    echo "User has succesfully logged back to ${_ctx}"
+    # Check to see if the server is up
+    ${OC_BINARY} whoami --request-timeout=$TIMEOUT /dev/null 2> /tmp/oc-whoami-err.temp
+    grep "Client.Timeout" /tmp/oc-whoami-err.temp > /dev/null 2>&1
+    _retCode=$?
+    rm -f /tmp/oc-whoami-err.temp
+    if [ $_retCode -ne 0 ]; then
+      local _ctx=$(${OC_BINARY} whoami -c)
+      local _cluster=$(${OC_BINARY} whoami --show-server)
+      local _user=$(${OC_BINARY} config view -o jsonpath='{.contexts[?(@.name == "'${_ctx}'")].context.user}' | cut -f 1 -d '/')
+      echo "oc login ${_cluster} -u ${_user} --request-timeout=2s"
+      ${OC_BINARY} login ${_cluster} -u ${_user} --request-timeout=$TIMEOUT
+      _retCode=$?
+      if [ $_retCode -eq 0 ]; then
+        ${OC_BINARY} config delete-context ${_ctx} > /dev/null 2>&1
+        ${OC_BINARY} config rename-context $(${OC_BINARY} whoami -c) ${_ctx} > /dev/null 2>&1
+        echo "User has succesfully logged back to ${_ctx}"
+      else
+        echo "There's been an error trying to log the user back in"
+      fi
+    else
+      echo "There's been a Timeout error trying to log the user back in. Is the server up and reachable?"
+    fi
   else
     echo "User is already logged in and valid. Context is $(${OC_BINARY} whoami -c)"
   fi
@@ -145,7 +160,7 @@ function use {
 }
 
 function use.help {
-  echo "Uses the specified context"
+  echo "Changes to the specified context"
   echo ""
   echo "Usage:"
   echo " $SCRIPT_NAME use <CONTEXT>"
